name: atomate2_pheasy
channels:
  - conda-forge
  - defaults
  - nodefaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - aioitertools=0.12.0
  - annotated-types=0.7.0
  - anyio=4.4.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.5
  - babel=2.17.0
  - backcall=0.2.0
  - bcrypt=4.2.1
  - beautifulsoup4=4.13.4
  - binutils=2.40
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blinker=1.9.0
  - boost=1.78.0
  - boost-cpp=1.78.0
  - boto3=1.36.2
  - botocore=1.36.2
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.1
  - c-compiler=1.7.0
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cffi=1.17.1
  - click=8.1.8
  - cmake=3.30.3
  - colorama=0.4.6
  - comm=0.2.2
  - compilers=1.7.0
  - cxx-compiler=1.7.0
  - debugpy=1.8.5
  - decorator=5.1.1
  - defusedxml=0.7.1
  - eigen=3.4.0
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fastapi=0.115.6
  - fastapi-cli=0.0.7
  - flask=3.1.0
  - fortran-compiler=1.7.0
  - fqdn=1.5.1
  - gcc=12.4.0
  - gcc_impl_linux-64=12.4.0
  - gcc_linux-64=12.4.0
  - gfortran=12.4.0
  - gfortran_impl_linux-64=12.4.0
  - gfortran_linux-64=12.4.0
  - gxx=12.4.0
  - gxx_impl_linux-64=12.4.0
  - gxx_linux-64=12.4.0
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.7
  - httptools=0.6.4
  - httpx=0.28.1
  - hyperframe=6.0.1
  - icu=73.2
  - importlib-metadata=8.4.0
  - importlib-resources=6.4.4
  - importlib_metadata=8.4.0
  - importlib_resources=6.4.4
  - intel-openmp=2021.4.0
  - ipykernel=6.30.1
  - ipython=8.12.0
  - isoduration=20.11.0
  - itsdangerous=2.2.0
  - jedi=0.19.1
  - jinja2=3.1.5
  - jmespath=1.0.1
  - json5=0.12.0
  - jsonlines=4.0.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.9.1
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-devel_linux-64=12.4.0
  - libgcc-ng=14.1.0
  - libgfortran=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libsanitizer=12.4.0
  - libsodium=1.0.20
  - libsqlite=3.46.1
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-devel_linux-64=12.4.0
  - libstdcxx-ng=14.1.0
  - libuuid=2.38.1
  - libuv=1.48.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - maggma=0.71.1
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mistune=3.1.3
  - mkl=2021.4.0
  - mkl-include=2024.2.1
  - mongogrant=0.3.3
  - mongomock=4.0.0
  - msgpack-python=1.1.0
  - nb_conda_kernels=2.5.1
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - notebook=7.4.4
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openssl=3.6.1
  - orjson=3.10.15
  - overrides=7.7.0
  - packaging=24.1
  - pandocfilters=1.5.0
  - paramiko=3.5.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pydantic=2.10.5
  - pydantic-core=2.27.2
  - pydantic-settings=2.7.1
  - pydash=8.0.5
  - pygments=2.18.0
  - pymongo=4.10.1
  - pynacl=1.5.0
  - pysocks=1.7.1
  - python=3.9.19
  - python-dotenv=1.0.1
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-multipart=0.0.20
  - python-tzdata=2024.2
  - python_abi=3.9
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rhash=1.4.4
  - rich=13.9.4
  - rich-toolkit=0.11.3
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.8
  - s3transfer=0.11.1
  - send2trash=1.8.3
  - sentinels=1.0.0
  - shellingham=1.5.4
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.7
  - spglib=2.5.0
  - sshtunnel=0.4.0
  - stack_data=0.6.2
  - starlette=0.41.3
  - sysroot_linux-64=2.17
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - typer=0.15.1
  - typer-slim=0.15.1
  - typer-slim-standard=0.15.1
  - types-python-dateutil=2.9.0.20250708
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - uri-template=1.3.0
  - uvicorn=0.34.0
  - uvicorn-standard=0.34.0
  - uvloop=0.20.0
  - watchfiles=1.0.4
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=14.2
  - werkzeug=3.1.3
  - wheel=0.44.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.1
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - alm==1.4.0
      - ase==3.22.1
      - async-timeout==4.0.3
      - atomate2==0.0.1.post2818+g17f56c97
      - attrs==24.2.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - chgnet==0.3.8
      - configargparse==1.7
      - contourpy==1.3.0
      - cryptography==43.0.1
      - custodian==2024.2.15
      - cycler==0.12.1
      - cython==3.0.11
      - dgl==2.1.0
      - dnspython==2.6.1
      - e3nn==0.4.4
      - emmet-core==0.84.2
      - f90nml==1.4.4
      - filelock==3.15.4
      - fireworks==2.0.6
      - flask-paginate==2024.4.12
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - future==1.0.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gunicorn==23.0.0
      - h5py==3.11.0
      - hiphive==1.3.1
      - idna==3.8
      - jobflow==0.1.19
      - joblib==1.4.2
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.7
      - latexcodec==3.0.0
      - lightning==2.4.0
      - lightning-utilities==0.11.7
      - llvmlite==0.43.0
      - mace-torch==0.3.6
      - matgl==1.1.3
      - matplotlib==3.9.2
      - matscipy==1.1.0
      - monty==2024.7.30
      - mp-api==0.45.7
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - numba==0.60.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py3==7.352.0
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.6.68
      - nvidia-nvtx-cu12==12.1.105
      - opt-einsum==3.3.0
      - opt-einsum-fx==0.1.4
      - palettable==3.3.3
      - pandas==2.2.2
      - pheasy==0.0.2
      - phonopy==2.28.0
      - pillow==10.4.0
      - plotly==5.24.1
      - prettytable==3.11.0
      - pybtex==0.24.0
      - pymatgen==2024.8.9
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-hostlist==1.23.0
      - pytorch-lightning==2.4.0
      - referencing==0.35.1
      - rpds-py==0.20.0
      - ruamel-yaml==0.17.20
      - ruamel-yaml-clib==0.2.12
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - seekpath==2.1.0
      - setuptools==75.1.0
      - smart-open==7.0.4
      - smmap==5.0.1
      - sympy==1.13.3
      - tabulate==0.9.0
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - torch==2.2.1
      - torch-ema==0.3
      - torchdata==0.7.1
      - torchmetrics==1.4.1
      - tqdm==4.66.5
      - trainstation==1.1
      - triton==2.2.0
      - tzdata==2024.1
      - uncertainties==3.2.2
      - urllib3==1.26.20
      - wrapt==1.16.0
      - yarl==1.9.11
prefix: /global/homes/h/hrushi99/.conda/envs/atomate2_pheasy
